spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2?useSSL=false&useUnicode=true&characterEncoding=utf8 #??utf-8???
    username: root
    password: 123456


  data:
      redis:
          # 连接地址
          host: "192.168.234.129"
          # 端口
          port: 6379
          # 数据库
          database: 0
          # 用户名，如果有
          # username:
          # 密码，如果有
          password: 5761665
          # 连接超时
          connect-timeout: 5s
          # 读超时
          timeout: 5s

          # Lettuce 客户端的配置
          lettuce:
            # 连接池配置
            pool:
              # 最小空闲连接
              min-idle: 0
              # 最大空闲连接
              max-idle: 8
              # 最大活跃连接
              max-active: 8
              # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
              max-wait: -1ms

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/study/file

server:
  port: 9004

mybatis-plus:
  type-aliases-package: com.example.dongruan.entity








